services:
- redis-server

language: python

python:
  - "2.6"
  - "2.7"
  - "pypy-5.3.1"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install Flask-Caching
  - python setup.py -q install
  - pip install codeclimate-test-reporter
  - pip install coverage

# command to run tests
script: nosetests
